apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: DeepSeek-R1-Distill-Llama-8B
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
  volumeMode: Filesystem