apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}