apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e5-small-v2
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
  volumeMode: Filesystem