apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e5-large-v2
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: default
  volumeMode: Filesystem