apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bge-reranker-v2-layerwise
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem