apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama3.1-8b
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual
  volumeMode: Filesystem