apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-llm-7b
  namespace: default
  labels:
    app: deepseek-llm-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-llm-7b
  template:
    metadata:
      labels:
        app: deepseek-llm-7b
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: deepseek-llm-7b
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      containers:
      - name: deepseek-llm-7b
        image: vllm/vllm-openai:v0.7.3
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve deepseek-ai/deepseek-llm-7b-chat --trust-remote-code --max-model-len 20000 --port 8002"
        ]
        ports:
        - containerPort: 8002
        resources:
          limits:
            cpu: "1"
            memory: 24G
            nvidia.com/gpu: "1"
          requests:
            cpu: "1"
            memory: 20G
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 120
          periodSeconds: 5